# Docker Compose to build and run
services:
  rateit-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rateit
    restart: unless-stopped
    container_name: rateit-app
    hostname: rateit-app
    ports: 
      - "7331:7331"
    environment:
      - FLASK_RUN_PORT=7331
      - FLASK_RUN_HOST=0.0.0.0
